version: 0.0
os: linux
files:
  - source: /
    destination: /frontend
hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
