# Generated by Django 3.2 on 2021-04-24 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
